### ISSUE TITLE
PDO error when generator factories

### ISSUE THREAD

**Issue by asivaneswaran** [TheDoctor0/laravel-factory-generator#20]
I get this error when I try to generate factories.
```
[2023-02-17 14:36:55] local.ERROR: PDO::prepare(): Argument #1 ($query) must be of type string, Illuminate\Database\Query\Expression given {"exception":"[object] (TypeError(code: 0): PDO::prepare(): Argument #1 ($query) must be of type string, Illuminate\\Database\\Query\\Expression given at /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414)
[stacktrace]
#0 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare(Object(Illuminate\\Database\\Query\\Expression))
#1 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}(Object(Illuminate\\Database\\Query\\Expression), Array)
#2 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback(Object(Illuminate\\Database\\Query\\Expression), Array, Object(Closure))
#3 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->run(Object(Illuminate\\Database\\Query\\Expression), Array, Object(Closure))
#4 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/thedoctor0/laravel-factory-generator/src/Database/EnumMysql.php(14): Illuminate\\Database\\Connection->select(Object(Illuminate\\Database\\Query\\Expression))
#5 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/thedoctor0/laravel-factory-generator/src/Database/EnumValues.php(21): TheDoctor0\\LaravelFactoryGenerator\\Database\\EnumMysql->values()
#6 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/thedoctor0/laravel-factory-generator/src/Database/EnumValues.php(13): TheDoctor0\\LaravelFactoryGenerator\\Database\\EnumValues->values(Object(App\\Models\\Landlord), 'user_id')
#7 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/thedoctor0/laravel-factory-generator/src/Console/GenerateFactoryCommand.php(314): TheDoctor0\\LaravelFactoryGenerator\\Database\\EnumValues::get(Object(App\\Models\\Landlord), 'user_id')
#8 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/thedoctor0/laravel-factory-generator/src/Console/GenerateFactoryCommand.php(264): TheDoctor0\\LaravelFactoryGenerator\\Console\\GenerateFactoryCommand->setProperty(Object(App\\Models\\Landlord), 'user_id', 'bigint')
#9 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/thedoctor0/laravel-factory-generator/src/Console/GenerateFactoryCommand.php(167): TheDoctor0\\LaravelFactoryGenerator\\Console\\GenerateFactoryCommand->getPropertiesFromTable(Object(App\\Models\\Landlord))
#10 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/thedoctor0/laravel-factory-generator/src/Console/GenerateFactoryCommand.php(113): TheDoctor0\\LaravelFactoryGenerator\\Console\\GenerateFactoryCommand->generateFactory('App\\\\Models\\\\Land...')
#11 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): TheDoctor0\\LaravelFactoryGenerator\\Console\\GenerateFactoryCommand->handle()
#12 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#14 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call(Array)
#17 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand(Object(TheDoctor0\\LaravelFactoryGenerator\\Console\\GenerateFactoryCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /Users/arasivaneswaran/Documents/repos/perso/landlord-helper/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
"} 
```

**Comment by fsay2604** [comment]
I get this error too executing `php artisan generate:factory`
Running Laravel v10.0.3 and laravel-factory-generator v1.2.4

**Comment by TheDoctor0** [comment]
Looks like something changed in Laravel 10. I'll check the changelog and prepare a fix.

**Comment by TheDoctor0** [comment]
@asivaneswaran, @fsay2604 it has been fixed in the [latest release](https://github.com/TheDoctor0/laravel-factory-generator/releases/tag/1.2.5).
